all: Frameworks/*.xcframework Frameworks/.symlinks
RUNTIME_URL?=@@URL@@
RUNTIME_SHA256?=@@SHA256@@
.cache/runtime.tar.gz:
	mkdir -p .cache
	curl --fail --location --retry 3 --connect-timeout 30 "$(RUNTIME_URL)" -o .cache/runtime.tar.gz.tmp
	printf '%s  %s\n' '$(RUNTIME_SHA256)' '.cache/runtime.tar.gz.tmp' | shasum -a 256 -c -
	mv .cache/runtime.tar.gz.tmp .cache/runtime.tar.gz
Frameworks/*.xcframework: .cache/runtime.tar.gz
	rm -rf Frameworks
	mkdir -p Frameworks
	tar -xzf .cache/runtime.tar.gz -C Frameworks
	touch Frameworks/*.xcframework
Frameworks/.symlinks: Frameworks/*.xcframework
	rm -rf Frameworks/.symlinks
	mkdir -p Frameworks/.symlinks/mpv
	sh create_framework_symlinks.sh Frameworks/Mpv.xcframework Frameworks/.symlinks/mpv
clean:
	rm -rf .cache Frameworks
.PHONY: all clean
